import { faInstagram, faInstagramSquare } from '@fortawesome/free-brands-svg-icons';
import { faAddressCard, faAngleDown, faAt, faBars, faCaretDown, faCertificate, faCheck, faChevronCircleRight, faChevronDown, faChevronLeft, faChevronRight, faCopy, faDownload, faEdit, faExclamation, faFile, faFileAlt, faFolder, faGlobe, faGlobeAsia, faHouseUser, faLandmark, faPlus, faPlusSquare, faRibbon, faSave, faScroll, faSearch, faSign, faSignInAlt, faSignOutAlt, faSpinner, faSquare, faTimes, faTrash, faUniversity, faUser, faUserGraduate, faUsersCog } from '@fortawesome/free-solid-svg-icons';
import { faFolder as farFolder, faFileAlt as farFileAlt } from '@fortawesome/free-regular-svg-icons';

const icons = [
    faCaretDown,
    faAngleDown,
    faBars,
    faTimes,
    faUser,
    faFileAlt,
    faFolder,
    faEdit,
    faCopy,
    faTrash,
    faSign,
    faSignInAlt,
    faInstagram,
    faInstagramSquare,
    faGlobe,
    faChevronRight,
    faChevronCircleRight,
    faChevronLeft,
    faFile,
    faFolder,
    farFolder,
    faUniversity,
    faScroll,
    faCertificate,
    faRibbon,
    faUserGraduate,
    faGlobeAsia,
    faFileAlt,
    farFileAlt,
    faDownload,
    faAddressCard,
    faAt,
    faHouseUser,
    faLandmark,
    faCheck,
    faSquare,
    faExclamation,
    faFolder,
    faChevronDown,
    faSave,
    faSpinner,
    faPlus,
    faSignOutAlt,
    faUsersCog,
    faPlusSquare,
    faSearch,
];

export default icons;